name: Build Java SDK

on:
  push:
    branches:
      - main

jobs:
  generate_schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build_rust:
    uses: ./.github/workflows/build-rust-cross-platform.yml

  build_java:
    name: Build Java
    runs-on: ubuntu-22.04
    needs:
      - generate_schemas
      - build_rust

    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Download Java schemas artifact
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: sdk-schemas-java
          path: languages/java/src/main/java/bit/sdk/schema/

      - name: Setup Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Download x86_64-apple-darwin files
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: libbitwarden_c_files-x86_64-apple-darwin
          path: languages/java/src/main/resources/darwin-x64

      - name: Download aarch64-apple-darwin files
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: libbitwarden_c_files-aarch64-apple-darwin
          path: languages/java/src/main/resources/darwin-aarch64

      - name: Download x86_64-unknown-linux-gnu files
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: libbitwarden_c_files-x86_64-unknown-linux-gnu
          path: languages/java/src/main/resources/ubuntu-x64

      - name: Download x86_64-pc-windows-msvc files
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: libbitwarden_c_files-x86_64-pc-windows-msvc
          path: languages/java/src/main/resources/windows-x64

      - name: Publish Maven
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2 # v2.11.1
        with:
          arguments: publish
          build-root-directory: languages/java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
