name: Go Release

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: "New Version"
        required: true

env:
  GO111MODULE: on
  GO_VERSION: "^1.18"

jobs:
  build_rust:
    uses: ./.github/workflows/build-rust-cross-platform.yml

  generate-schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build:
    name: Build
    needs:
      - build_rust
      - generate-schemas
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Go environment
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  release:
    name: Release
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Go environment
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set release version
        run: echo "VERSION=${{ github.event.inputs.version_number }}" >> $GITHUB_ENV

      - name: Install Goreleaser
        run: go install github.com/goreleaser/goreleaser@v1.21.2

      - name: Run Goreleaser
        run: goreleaser release --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
