name: Deploy NuGet Package

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: "New Version"
        required: true

jobs:
  generate_schemas:
    uses: ./.github/workflows/generate_schemas.yml

  build_rust:
    uses: ./.github/workflows/build-rust-cross-platform.yml

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs:
      - generate_schemas
      - build_rust

    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Download C# schemas artifact
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: schemas.cs
          path: languages/csharp/Bitwarden.Sdk

      - name: Set up .NET Core
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
        with:
          global-json-file: languages/csharp/global.json

      - name: Download x86_64-apple-darwin files
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: libbitwarden_c_files-x86_64-apple-darwin
          path: languages/csharp/Bitwarden.Sdk/macos-x64

      - name: Download aarch64-apple-darwin files
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: libbitwarden_c_files-aarch64-apple-darwin
          path: languages/csharp/Bitwarden.Sdk/macos-arm64

      - name: Download x86_64-unknown-linux-gnu files
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: libbitwarden_c_files-x86_64-unknown-linux-gnu
          path: languages/csharp/Bitwarden.Sdk/ubuntu-x64

      - name: Download x86_64-pc-windows-msvc files
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          name: libbitwarden_c_files-x86_64-pc-windows-msvc
          path: languages/csharp/Bitwarden.Sdk/windows-x64

      - name: Pack NuGet Package
        env:
          VERSION: ${{ github.event.inputs.version_number }}
        run: dotnet pack --configuration Release -p:PackageID=Bitwarden.Sdk -p:Version=${VERSION} --output ./nuget-output /nologo /v:n
        working-directory: languages/csharp/Bitwarden.Sdk

      - name: Publish NuGet Package
        run: dotnet nuget push ./languages/csharp/Bitwarden.Sdk/nuget-output/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
